
name: 
on:
  pull_request:
    branches:
      - main
    types: [closed]
    
jobs:
  tag:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    env:
      pr: ${{ github.event.pull_request }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: env
        run: env 
